# Sports Cars Price Analysis

## About Dataset

This dataset contains information about the prices of different sports cars from various manufacturers. The dataset includes the make and model of the car, the year of production, the engine size, the horsepower, the torque, the 0-60 MPH time, and the price in USD. The dataset is useful for analyzing the prices of different sports cars and identifying trends in the market.
Columns
1. Car Make: The make of the sports car, which represents the brand or company that produced the car. Examples of car makes in this dataset include Porsche, Lamborghini, Ferrari, Audi, and McLaren.
2. Car Model: The model of the sports car, which represents the specific version or variant of the car produced by the manufacturer. Examples of car models in this dataset include 911, Huracan, 488 GTB, R8, 720S, M8, AMG GT, Corvette, Mustang Shelby GT500, and GT-R Nismo.
3. Year: The year of production of the sports car, which indicates the model year when the car was first introduced or made available for purchase.
4. Engine Size (L): The size of the sports car's engine in liters, which represents the volume of the engine's cylinders. A larger engine size typically indicates higher power and performance. Engine sizes in this dataset range from 2.0L to 8.0L, with some cars having electric motors instead.
5. Horsepower: The horsepower of the sports car, which represents the power output of the car's engine. Higher horsepower typically indicates faster acceleration and higher top speed. Horsepower values in this dataset range from 300 to 1479.
6. Torque (lb-ft): The torque of the sports car in pound-feet, which represents the rotational force generated by the engine. Higher torque values typically indicate stronger acceleration and better handling. Torque values in this dataset range from 270 to 1180.
7. 0-60 MPH Time (seconds): The time it takes for the sports car to accelerate from 0 to 60 miles per hour, which is a common measure of acceleration and performance. Lower 0-60 MPH times typically indicate faster acceleration and better performance. 0-60 MPH times in this dataset range from 1.85 to 5.3 seconds.
8. Price (in USD): The price of the sports car in US dollars, which represents the cost of purchasing the car. Prices in this dataset range from $25,000 to $3,000,000.

Source: https://www.kaggle.com/datasets/rkiattisak/sports-car-prices-dataset

## Importing importatnt Libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
%matplotlib inline

## Section - 1: Importing the DataSet

In [3]:
sportscar = pd.read_csv('Sport car price.csv')

# Section 2: exploring the Dataset

In [19]:
sportscar.head(100)

,Car Make,Car Model,Year,Engine Size (L),Horsepower,Torque (lb-ft),0-60 MPH Time (seconds),Price (in USD)
0,Porsche,911,2022,3,379,331,4,"101,200"
1,Lamborghini,Huracan,2021,5.2,630,443,2.8,"274,390"
2,Ferrari,488 GTB,2022,3.9,661,561,3,"333,750"
3,Audi,R8,2022,5.2,562,406,3.2,"142,700"
4,McLaren,720S,2021,4,710,568,2.7,"298,000"
...,...,...,...,...,...,...,...,...
95,Pagani,Huayra,2022,6,764,738,2.8,"2,800,000"
96,Porsche,718 Cayman GT4,2022,4,414,309,4.2,"100,550"
97,Rimac,Nevera,2022,Electric,1914,1696,1.95,"2,400,000"
98,Rolls-Royce,Wraith,2021,6.8,624,605,4.4,"330,000"
99,Tesla,Roadster,2022,Electric,1000+,737,1.9,"200,000"

In [9]:
type(sportscar)

pandas.core.frame.DataFrame

In [10]:
sportscar.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1007 entries, 0 to 1006
Data columns (total 8 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Car Make                 1007 non-null   object
 1   Car Model                1007 non-null   object
 2   Year                     1007 non-null   int64
 3   Engine Size (L)          997 non-null    object
 4   Horsepower               1007 non-null   object
 5   Torque (lb-ft)           1004 non-null   object
 6   0-60 MPH Time (seconds)  1007 non-null   object
 7   Price (in USD)           1007 non-null   object
dtypes: int64(1), object(7)
memory usage: 63.1+ KB

### Lets check what kinds of value does different colums hold.

In [18]:
sportscar.value_counts('Engine Size (L)')

Engine Size (L)
4                       219
6.2                     113
3                        85
3.5                      79
5                        68
6.5                      46
3.8                      38
Electric                 36
3.7                      35
2                        34
2.9                      30
3.9                      30
5.2                      29
6                        28
2.5                      25
8                        23
4.7                      23
4.4                      11
6.8                       6
1.7                       4
8.4                       3
Electric Motor            3
1.8                       3
6.6                       3
Hybrid                    2
1.5                       2
Electric (100 kWh)        1
Electric (93 kWh)         1
Electric (tri-motor)      1
7                         1
6.7                       1
-                         1
6.4                       1
6.3                       1
5.7                       1
5.5                       1
0                         1
4.6                       1
4.0 (Hybrid)              1
3.6                       1
3.3                       1
2.3                       1
2.0 (Electric)            1
1.5 + Electric            1
Hybrid (4.0)              1
dtype: int64

In [15]:
sportscar.value_counts('Horsepower')

Horsepower
503      45
591      39
650      31
660      30
416      29
         ..
1,020     1
485       1
550       1
621       1
482       1
Length: 124, dtype: int64

In [16]:
sportscar.value_counts('Torque (lb-ft)')

Torque (lb-ft)
590    71
443    47
406    42
516    38
650    36
       ..
440     1
442     1
0       1
475     1
944     1
Length: 93, dtype: int64

In [17]:
sportscar.value_counts('0-60 MPH Time (seconds)')

0-60 MPH Time (seconds)
3.5      153
3.8       70
2.9       62
2.8       58
3.6       51
3.1       50
2.5       48
4         42
4.4       37
3         37
3.2       35
4.2       32
4.9       26
4.1       25
3.3       23
2.7       22
3.4       21
3.9       21
3.7       21
4.7       20
1.9       19
4.8       15
2.4       14
2.6       13
5         11
5.4       10
4.3        8
4.5        8
1.85       7
5.3        7
5.2        7
5.1        7
2.3        7
4.6        6
1.98       5
1.8        2
2.2        1
2.1        1
2          1
1.95       1
6.4        1
6.5        1
< 1.9      1
dtype: int64